title: Thejas Kempegowda
logo: docs/assets/Thejas_Image.png
description: 🚀 Full-stack developer with 5 years of experience in Angular, TypeScript, React, JavaScript, Java, .NET, Spring Boot, Azure & AWS. 🎯 Mastering AI & ML at Stony Brook to build smart, scalable solutions!
theme: jekyll-theme-minimal
